import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import{planIdentityFix,applyIdentityFix,verifyIdentityFix}from'./identity.mjs';
const facts={business:'Example Company',website:'https://example.com/',foundingYear:'2018',confirmed:true};
const raw=JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'Organization',name:'Example Company',url:'https://example.com/'}]});
const h=s=>`'sha256-${createHash('sha256').update(s).digest('base64')}'`;
const html=`<!doctype html><meta http-equiv="Content-Security-Policy" content="script-src 'self' ${h(raw)}"><h1>Keep this copy</h1><script type="application/ld+json">${raw}</script>`;
test('confirmed facts produce a bounded draft and an updated CSP; recheck passes',()=>{const p=planIdentityFix(html,'https://example.com/service/',facts);assert.equal(p.status,'draft-ready');const after=applyIdentityFix(html,p);assert.ok(after.includes('<h1>Keep this copy</h1>'));assert.ok(!after.includes(h(raw)));assert.equal(verifyIdentityFix(after,'https://example.com/service/',facts).status,'verified');assert.equal(planIdentityFix(after,'https://example.com/service/',facts).changes.length,0);});
test('unconfirmed facts, wrong domains, stale source, and tampered drafts cannot be applied',()=>{assert.throws(()=>planIdentityFix(html,'https://example.com/',{...facts,confirmed:false}));assert.throws(()=>planIdentityFix(html,'https://other.com/',facts));const p=planIdentityFix(html,'https://example.com/',facts);assert.throws(()=>applyIdentityFix(html+' ',p));assert.throws(()=>applyIdentityFix(html,{...p,draftHTML:'tampered'}));});
test('existing conflicting dates and unsupported CSP require review without silent overwrites',()=>{const different=html.replace(raw,raw.replace('"url":','"foundingDate":"2010","url":'));const p=planIdentityFix(different,'https://example.com/',facts);assert.equal(p.status,'conflict');assert.equal(p.draftHTML,different);const unsupported=html.replace(h(raw),"'none'");assert.equal(planIdentityFix(unsupported,'https://example.com/',facts).status,'blocked');});
test('other organizations and missing schema are not invented or modified',()=>{const other=html.replaceAll('Example Company','Other Company');assert.equal(planIdentityFix(other,'https://example.com/',facts).status,'not-supported');assert.equal(planIdentityFix('<h1>Hi</h1>','https://example.com/',facts).status,'not-supported');});
