import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import Stripe from 'stripe';
import {publicAddress,websiteURL,analyzeHTML,audit} from './audit.mjs';import {createStore} from './store.mjs';import {createPortal} from './server.mjs';
const input={business:'Example Plumbing',location:'Houston',service:'Plumbing',website:'https://example.com/'};const token='x'.repeat(40);const report=analyzeHTML('<title>Example plumbing</title><meta name="description" content="Houston plumbing"><body><h1>Plumbing in Houston</h1><a href="tel:123">Call</a></body>','https://example.com',input);
test('SSRF rejects private, reserved, metadata, IPv6 and non-HTTPS targets',()=>{for(const a of ['127.0.0.1','10.1.2.3','169.254.169.254','172.16.0.2','192.168.0.1','100.64.0.1','0.0.0.0','224.0.0.1','::1','::ffff:127.0.0.1'])assert.equal(publicAddress(a),false,a);assert.equal(publicAddress('8.8.8.8'),true);for(const u of ['http://example.com','https://localhost','https://127.1','https://user:pass@example.com','https://example.com:8443'])assert.throws(()=>websiteURL(u));});
test('observations preserve evidence and never claim AI recommendation',()=>{assert.equal(report.cards.length,5);assert.match(report.summary,/not an AI visibility score/);assert.equal(report.cards[4].status,'needs-review');const noindex=analyzeHTML('<meta name="robots" content="noindex"><h1>A</h1>','https://example.com',input);assert.equal(noindex.cards[3].status,'needs-review');});
test('crawler respects robots and fails closed when permission is unavailable',async()=>{let calls=0;await assert.rejects(audit(input,{fetcher:async()=>{calls++;return{status:200,body:'User-agent: *\nDisallow: /'};}}),/not to crawl/);assert.equal(calls,1);await assert.rejects(audit(input,{fetcher:async()=>({status:503})}),/permission/);});
test('private keys and quotas persist across restart',()=>{const dir=mkdtempSync(join(tmpdir(),'flp-'));try{let s=createStore(join(dir,'test.sqlite'));const j=s.create(input);assert.ok(s.get(j.id,j.secret));assert.equal(s.get(j.id,'wrong'),undefined);assert.equal(s.quota('q',1,60000),true);s.close();s=createStore(join(dir,'test.sqlite'));assert.equal(s.quota('q',1,60000),false);assert.ok(s.get(j.id,j.secret));s.close();}finally{rmSync(dir,{recursive:true,force:true});}});
async function fixture(t,extra={}){const store=createStore();const app=createPortal({env:{FLP_OPERATOR_TOKEN:token,PUBLIC_ORIGIN:'http://portal.test',...extra.env},store,run:async()=>report,...extra,env:{FLP_OPERATOR_TOKEN:token,PUBLIC_ORIGIN:'http://portal.test',...extra.env}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;t.after(async()=>{await new Promise(r=>app.server.close(r));store.close();});const req=(path,{method='GET',body,secret,operator=false,headers={}}={})=>fetch(base+path,{method,headers:{'content-type':'application/json',Origin:'http://portal.test',...(operator?{Authorization:`Bearer ${token}`}:{ }),...(secret?{'X-Report-Key':secret}:{}),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});return{...app,req};}
test('full private journey: queued audit, access isolation, fit, checkout, signed payment, onboarding',async t=>{
 const verifier=new Stripe('sk_test_fixture_not_a_real_key');let sessions=0;const stripe={webhooks:verifier.webhooks,checkout:{sessions:{create:async(p)=>{sessions++;assert.equal(p.line_items[0].price_data.unit_amount,200000);assert.equal(p.mode,'payment');assert.equal(p.payment_method_types,undefined);return{id:'cs_fixture',url:'https://checkout.stripe.com/example'};},retrieve:async()=>({status:'open',url:'https://checkout.stripe.com/example'})}}};
 const {req,work,store}=await fixture(t,{stripe,env:{STRIPE_WEBHOOK_SECRET:'whsec_fixture'}});
 assert.equal((await req('/api/checks',{method:'POST',body:input})).status,503);
 const j=await(await req('/api/checks',{method:'POST',body:input,operator:true})).json();await work();const path=`/api/reports/${j.id}`;
 assert.equal((await req(path)).status,404);assert.equal((await req(path,{secret:'bad'})).status,404);assert.equal((await(await req(path,{secret:j.secret})).json()).status,'ready');
 assert.equal((await req(path+'/checkout',{method:'POST',secret:j.secret,body:{acceptedScope:true}})).status,409);
 assert.equal((await req(path+'/approve',{method:'POST',secret:j.secret,body:{}})).status,403);
 assert.equal((await req(path+'/approve',{method:'POST',operator:true,body:{}})).status,200);
 assert.equal((await req(path+'/checkout',{method:'POST',secret:j.secret,body:{acceptedScope:true}})).status,200);
 assert.equal((await req(path+'/checkout',{method:'POST',secret:j.secret,body:{acceptedScope:true}})).status,200);assert.equal(sessions,1);
 assert.equal((await req(path+'/onboarding',{method:'POST',secret:j.secret,body:{}})).status,403);
 const payload=JSON.stringify({id:'evt_fixture',type:'checkout.session.completed',data:{object:{id:'cs_fixture',metadata:{flp_job:j.id},mode:'payment',payment_status:'paid',currency:'usd',amount_total:200000}}});const signature=verifier.webhooks.generateTestHeaderString({payload,secret:'whsec_fixture'});
 assert.equal((await req('/api/stripe-webhook',{method:'POST',body:payload,headers:{'stripe-signature':'bad'}})).status,400);
 for(let i=0;i<2;i++)assert.equal((await req('/api/stripe-webhook',{method:'POST',body:payload,headers:{'stripe-signature':signature}})).status,200);
 assert.equal(store.db.prepare('SELECT count(*) n FROM events').get().n,1);
 const details={contactName:'Client',email:'client@example.com',websitePlatform:'WordPress',profileURL:'https://example.com',priority:'Service page',approvalContact:'Owner'};
 assert.equal((await req(path+'/onboarding',{method:'POST',secret:j.secret,body:details})).status,200);assert.equal((await(await req(path,{secret:j.secret})).json()).onboarded,true);
});
test('public challenge verifies hostname/action before creating a job; failed scans stay unavailable',async t=>{const {req,work,store}=await fixture(t,{env:{PUBLIC_SCANS:'true',TURNSTILE_SECRET_KEY:'fixture',TURNSTILE_SITE_KEY:'fixture'},verify:async()=>({success:true,hostname:'evil.test',action:'audit'}),run:async()=>{throw Error('blocked');}});assert.equal((await req('/api/checks',{method:'POST',body:{...input,challenge:'x'}})).status,403);assert.equal(store.db.prepare('SELECT count(*) n FROM jobs').get().n,0);const j=await(await req('/api/checks',{method:'POST',body:input,operator:true})).json();await work();const r=await(await req(`/api/reports/${j.id}`,{secret:j.secret})).json();assert.equal(r.status,'unavailable');assert.match(r.report.message,/not a negative result/);});
