import{makeDraft,renderBody,renderDocument,plainText,safeLink}from'/assets/service-page.mjs?v=2';
const $=id=>document.getElementById(id);let draft=null,approved=false;
const say=s=>$('status').textContent=s;
function invalidate(){draft=null;approved=false;$('approval').checked=false;$('export').disabled=true;$('copy').disabled=true;$('review').hidden=true;}
function fail(text){$('form-error').textContent=text;$('form-error').hidden=false;$('form-error').focus();}
function clearErrors(){$('form-error').hidden=true;for(const el of $('draft-form').elements)el.removeAttribute('aria-invalid');}
function preview(f){draft=makeDraft(f);$('preview-title').textContent=draft.heading;$('preview-intro').textContent=draft.intro;$('preview-body').innerHTML=renderBody(draft);$('search-title').textContent=draft.title;$('search-description').textContent=draft.description;$('review').hidden=false;$('copy').disabled=false;say('Your draft is ready. Review the facts, scope, and links before approving it.');$('review').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
$('draft-form').addEventListener('input',e=>{invalidate();e.target.removeAttribute('aria-invalid');});
$('draft-form').onsubmit=e=>{e.preventDefault();clearErrors();try{
 const f=Object.fromEntries(new FormData(e.target));const labels={business:'Business name',website:'Your website',service:'Service',audience:'Customer type',location:'Service area',summary:'Offer description',deliverables:'Deliverables',process:'Getting started',limits:'Before buying',pageURL:'Planned page address',contact:'Contact link',cta:'Button text'};
 const missing=[];for(const el of e.target.elements){if(el.required&&!el.checkValidity()){el.setAttribute('aria-invalid','true');missing.push(el.id==='facts-confirmed'?'Confirm your business details':labels[el.name]||el.name);}}
 if(missing.length){fail('Please complete: '+missing.join(', ')+'.');return;}
 for(const name of ['website','pageURL','contact']){try{f[name]=safeLink(f[name]);e.target.elements[name].value=f[name];}catch{e.target.elements[name].setAttribute('aria-invalid','true');fail(`${labels[name]} needs a valid website address, such as yourbusiness.com. HTTPS is added automatically; login details and other link types are not accepted.`);return;}}
 f.confirmed=$('facts-confirmed').checked;preview(f);
 }catch(e){fail(e.message);}};
$('example').onclick=()=>{invalidate();clearErrors();preview({confirmed:true,business:'FLP Marketing Group',service:'AI search and local business visibility',audience:'Established service businesses with an existing website',location:'Houston-based',summary:'Help customers understand what you do, where you work, and how to take the next step. FLP improves business information on websites and local profiles.',deliverables:['Website and business-profile review','One existing service-page update within an agreed scope','Inquiry measurement setup'],process:'Start with a free draft. For managed work, FLP confirms access, scope, availability, and costs before starting.',limits:'The free draft does not publish to a website. Managed implementation is separate. Rankings, AI recommendations, traffic, and leads are not guaranteed.',cta:'Explore FLP',website:'https://flpmarketinggroup.com/',pageURL:'https://flpmarketinggroup.com/ai-search-visibility/',contact:'https://flpmarketinggroup.com/ai-search-visibility/'});say('FLP example ready. These are our public business details. Enter your own details above to build your page.');};
$('approval').onchange=()=>{approved=$('approval').checked;$('export').disabled=!approved||!draft;};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(plainText(draft));say('Page copy copied.');}catch{say('Copy was unavailable. You can select the draft text or download the approved page.');}};
$('export').onclick=()=>{try{const text=renderDocument(draft,{approved});const url=URL.createObjectURL(new Blob([text],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download='service-page.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);say('Download requested. Check your browser’s downloads for service-page.html. It is not published to your website.');}catch(e){say(e.message);}};
